<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.openbear.tool.autotest</groupId>
    <artifactId>autotest-spi-plugins-built-in</artifactId>
    <version>1.0.0</version>
  </parent>
  <artifactId>db-oracle-plugin</artifactId>
  <dependencies>
    <dependency>
      <groupId>org.openbear.tool.autotest</groupId>
      <artifactId>autotest-spi</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.openbear.tool.autotest</groupId>
      <artifactId>autotest-jdbc</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.openbear.tool.autotest</groupId>
      <artifactId>autotest-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.zaxxer</groupId>
      <artifactId>HikariCP</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
