<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>org.openbear.tool.autotest</groupId><artifactId>autotest-spi-plugins-built-in</artifactId><version>1.0.0</version></parent><artifactId>msg-activemq-plugin</artifactId><dependencies><dependency><groupId>org.projectlombok</groupId><artifactId>lombok</artifactId><scope>provided</scope></dependency><dependency><groupId>org.openbear.tool.autotest</groupId><artifactId>autotest-spi</artifactId><version>${project.version}</version></dependency><dependency><groupId>org.openbear.tool.autotest</groupId><artifactId>autotest-core</artifactId><version>${project.version}</version></dependency><dependency><groupId>org.apache.activemq</groupId><artifactId>activemq-client</artifactId></dependency><dependency><groupId>org.slf4j</groupId><artifactId>slf4j-api</artifactId></dependency></dependencies></project>
