<project xmlns="http://maven.apache.org/POM/4.0.0">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.openbear.tool.autotest</groupId>
		<artifactId>autotest-parent</artifactId>
		<version>1.0.0</version>
	</parent>
	<artifactId>autotest-cli</artifactId>
	<dependencies>
		<dependency>
			<groupId>org.openbear.tool.autotest</groupId>
			<artifactId>autotest-spi</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openbear.tool.autotest</groupId>
			<artifactId>autotest-core</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openbear.tool.autotest</groupId>
			<artifactId>autotest-dsl</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openbear.tool.autotest</groupId>
			<artifactId>autotest-jdbc</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openbear.tool.autotest</groupId>
			<artifactId>http-client-plugin</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openbear.tool.autotest</groupId>
			<artifactId>db-mysql-plugin</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openbear.tool.autotest</groupId>
			<artifactId>db-oracle-plugin</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openbear.tool.autotest</groupId>
			<artifactId>msg-activemq-plugin</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openbear.tool.autotest</groupId>
			<artifactId>reporting-default-plugin</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.openbear.tool.autotest</groupId>
			<artifactId>autotest-external-plugin-fixture</artifactId>
			<version>${project.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>info.picocli</groupId>
			<artifactId>picocli</artifactId>
			<version>${picocli.version}</version>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>${logback.version}</version>
			<scope>runtime</scope>
		</dependency>
	</dependencies>
</project>
